import type { Asset } from "@/types/domain";
import { daysAgo, daysFromNow } from "./dates";

export const ASSETS: Asset[] = [
  // Solaris Retail Group
  {
    id: "ast-sol-01",
    workspaceId: "ws-solaris",
    name: "Dell Latitude 5440 Laptop",
    category: "Computers",
    serialNumber: "DL5440-SR-001",
    assignedTo: "Amara Nwosu",
    purchaseDate: daysAgo(400),
    currentValue: 480000,
    condition: "good",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: daysFromNow(14),
  },
  {
    id: "ast-sol-02",
    workspaceId: "ws-solaris",
    name: "Dell Latitude 5440 Laptop",
    category: "Computers",
    serialNumber: "DL5440-SR-002",
    assignedTo: "Ifeoma Eze",
    purchaseDate: daysAgo(400),
    currentValue: 480000,
    condition: "good",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: daysFromNow(210),
  },
  {
    id: "ast-sol-03",
    workspaceId: "ws-solaris",
    name: "Toyota Hiace Delivery Van",
    category: "Vehicles",
    serialNumber: "TH-VAN-SR-01",
    assignedTo: "Logistics Team",
    purchaseDate: daysAgo(720),
    currentValue: 12500000,
    condition: "fair",
    location: "Lagos Warehouse",
    status: "in_use",
    warrantyExpiry: null,
  },
  {
    id: "ast-sol-04",
    workspaceId: "ws-solaris",
    name: "Verifone POS Terminal",
    category: "POS Systems",
    serialNumber: "VF-POS-SR-014",
    assignedTo: "Store 3 — Lekki",
    purchaseDate: daysAgo(180),
    currentValue: 210000,
    condition: "excellent",
    location: "Lekki Branch",
    status: "in_use",
    warrantyExpiry: daysFromNow(185),
  },
  {
    id: "ast-sol-05",
    workspaceId: "ws-solaris",
    name: "HP LaserJet Pro Printer",
    category: "Office Equipment",
    serialNumber: "HP-LJ-SR-009",
    assignedTo: null,
    purchaseDate: daysAgo(500),
    currentValue: 145000,
    condition: "fair",
    location: "Lagos HQ",
    status: "in_storage",
    warrantyExpiry: daysAgo(30),
  },
  {
    id: "ast-sol-06",
    workspaceId: "ws-solaris",
    name: "Server Rack — Dell PowerEdge",
    category: "Servers & Networking",
    serialNumber: "DPE-SRV-SR-01",
    assignedTo: null,
    purchaseDate: daysAgo(600),
    currentValue: 3200000,
    condition: "good",
    location: "Lagos HQ Server Room",
    status: "in_use",
    warrantyExpiry: daysFromNow(95),
  },
  {
    id: "ast-sol-07",
    workspaceId: "ws-solaris",
    name: "Executive Office Desk Set",
    category: "Furniture",
    serialNumber: "FUR-SR-022",
    assignedTo: "Chibueze Okafor",
    purchaseDate: daysAgo(900),
    currentValue: 620000,
    condition: "excellent",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: null,
  },
  {
    id: "ast-sol-08",
    workspaceId: "ws-solaris",
    name: "Toyota Hiace Delivery Van",
    category: "Vehicles",
    serialNumber: "TH-VAN-SR-02",
    assignedTo: null,
    purchaseDate: daysAgo(1100),
    currentValue: 7800000,
    condition: "poor",
    location: "Lagos Warehouse",
    status: "under_repair",
    warrantyExpiry: null,
  },
  {
    id: "ast-sol-09",
    workspaceId: "ws-solaris",
    name: "iPhone 14 — Field Sales",
    category: "Mobile Devices",
    serialNumber: "IP14-SR-005",
    assignedTo: "Amara Nwosu",
    purchaseDate: daysAgo(260),
    currentValue: 610000,
    condition: "excellent",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: daysFromNow(105),
  },
  {
    id: "ast-sol-10",
    workspaceId: "ws-solaris",
    name: "Verifone POS Terminal",
    category: "POS Systems",
    serialNumber: "VF-POS-SR-015",
    assignedTo: "Store 1 — Ikeja",
    purchaseDate: daysAgo(180),
    currentValue: 210000,
    condition: "good",
    location: "Ikeja Branch",
    status: "in_use",
    warrantyExpiry: daysFromNow(185),
  },
  {
    id: "ast-sol-11",
    workspaceId: "ws-solaris",
    name: "Retired Dell Optiplex Desktop",
    category: "Computers",
    serialNumber: "DO-SR-003",
    assignedTo: null,
    purchaseDate: daysAgo(1600),
    currentValue: 40000,
    condition: "poor",
    location: "Lagos HQ Storage",
    status: "retired",
    warrantyExpiry: null,
  },
  {
    id: "ast-sol-12",
    workspaceId: "ws-solaris",
    name: "Warehouse Shelving System",
    category: "Fixtures",
    serialNumber: "WH-SHLF-SR-01",
    assignedTo: null,
    purchaseDate: daysAgo(800),
    currentValue: 980000,
    condition: "good",
    location: "Lagos Warehouse",
    status: "in_use",
    warrantyExpiry: null,
  },
  // Vertex Logistics Ltd
  {
    id: "ast-vtx-01",
    workspaceId: "ws-vertex",
    name: "MAN TGS Cargo Truck",
    category: "Fleet Vehicles",
    serialNumber: "MAN-TGS-VX-01",
    assignedTo: "Fleet Team A",
    purchaseDate: daysAgo(500),
    currentValue: 38000000,
    condition: "good",
    location: "Apapa Depot",
    status: "in_use",
    warrantyExpiry: daysFromNow(9),
  },
  {
    id: "ast-vtx-02",
    workspaceId: "ws-vertex",
    name: "MAN TGS Cargo Truck",
    category: "Fleet Vehicles",
    serialNumber: "MAN-TGS-VX-02",
    assignedTo: "Fleet Team B",
    purchaseDate: daysAgo(500),
    currentValue: 38000000,
    condition: "fair",
    location: "Apapa Depot",
    status: "in_use",
    warrantyExpiry: daysFromNow(9),
  },
  {
    id: "ast-vtx-03",
    workspaceId: "ws-vertex",
    name: "Forklift — Toyota 8FG25",
    category: "Warehouse Equipment",
    serialNumber: "TFG25-VX-01",
    assignedTo: "Warehousing Team",
    purchaseDate: daysAgo(350),
    currentValue: 5600000,
    condition: "good",
    location: "Ikorodu Warehouse",
    status: "in_use",
    warrantyExpiry: daysFromNow(260),
  },
  {
    id: "ast-vtx-04",
    workspaceId: "ws-vertex",
    name: "GPS Fleet Tracking Hub",
    category: "Servers & Networking",
    serialNumber: "GPS-HUB-VX-01",
    assignedTo: null,
    purchaseDate: daysAgo(300),
    currentValue: 1400000,
    condition: "excellent",
    location: "Apapa Depot",
    status: "in_use",
    warrantyExpiry: daysFromNow(150),
  },
  {
    id: "ast-vtx-05",
    workspaceId: "ws-vertex",
    name: "Dell Latitude 5440 Laptop",
    category: "Computers",
    serialNumber: "DL5440-VX-001",
    assignedTo: "Emeka Chukwu",
    purchaseDate: daysAgo(380),
    currentValue: 480000,
    condition: "good",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: daysFromNow(240),
  },
  {
    id: "ast-vtx-06",
    workspaceId: "ws-vertex",
    name: "MAN TGS Cargo Truck",
    category: "Fleet Vehicles",
    serialNumber: "MAN-TGS-VX-03",
    assignedTo: null,
    purchaseDate: daysAgo(1300),
    currentValue: 21000000,
    condition: "poor",
    location: "Apapa Depot",
    status: "under_repair",
    warrantyExpiry: null,
  },
  {
    id: "ast-vtx-07",
    workspaceId: "ws-vertex",
    name: "Office Furniture Set — HQ",
    category: "Furniture",
    serialNumber: "FUR-VX-011",
    assignedTo: null,
    purchaseDate: daysAgo(700),
    currentValue: 540000,
    condition: "good",
    location: "Lagos HQ",
    status: "in_use",
    warrantyExpiry: null,
  },
  {
    id: "ast-vtx-08",
    workspaceId: "ws-vertex",
    name: "Cold Chain Refrigerated Trailer",
    category: "Fleet Vehicles",
    serialNumber: "CCT-VX-01",
    assignedTo: "Fleet Team C",
    purchaseDate: daysAgo(220),
    currentValue: 26500000,
    condition: "excellent",
    location: "Ikorodu Warehouse",
    status: "in_use",
    warrantyExpiry: daysFromNow(320),
  },
  {
    id: "ast-vtx-09",
    workspaceId: "ws-vertex",
    name: "Retired Forklift — Toyota 7FG20",
    category: "Warehouse Equipment",
    serialNumber: "TFG20-VX-01",
    assignedTo: null,
    purchaseDate: daysAgo(1800),
    currentValue: 250000,
    condition: "poor",
    location: "Ikorodu Warehouse",
    status: "retired",
    warrantyExpiry: null,
  },
  {
    id: "ast-vtx-10",
    workspaceId: "ws-vertex",
    name: "iPhone 14 — Dispatch Lead",
    category: "Mobile Devices",
    serialNumber: "IP14-VX-002",
    assignedTo: "Segun Afolabi",
    purchaseDate: daysAgo(200),
    currentValue: 610000,
    condition: "excellent",
    location: "Apapa Depot",
    status: "in_use",
    warrantyExpiry: daysFromNow(165),
  },
];

export function getAssetsForWorkspace(workspaceId: string) {
  return ASSETS.filter((a) => a.workspaceId === workspaceId);
}
