import type { Client } from "@/types/domain";
import { daysAgo } from "./dates";

export const CLIENTS: Client[] = [
  // Solaris Retail Group
  {
    id: "cli-sol-01",
    workspaceId: "ws-solaris",
    name: "Zenith Marketplace",
    industry: "Retail",
    primaryContact: "Chidera Obi",
    email: "chidera@zenithmarketplace.ng",
    phone: "+234 701 668 2290",
    status: "active",
    projectsCount: 3,
    invoicesCount: 12,
    revenueGenerated: 24500000,
    lastInteraction: daysAgo(2),
    accountOwner: "Amara Nwosu",
  },
  {
    id: "cli-sol-02",
    workspaceId: "ws-solaris",
    name: "Ivory Home Stores",
    industry: "Home & Living Retail",
    primaryContact: "Blessing Nkem",
    email: "blessing@ivoryhome.ng",
    phone: "+234 802 118 4471",
    status: "active",
    projectsCount: 2,
    invoicesCount: 9,
    revenueGenerated: 15200000,
    lastInteraction: daysAgo(6),
    accountOwner: "Amara Nwosu",
  },
  {
    id: "cli-sol-03",
    workspaceId: "ws-solaris",
    name: "Northern Star Traders",
    industry: "Wholesale",
    primaryContact: "Sadiq Bello",
    email: "sadiq@northernstar.ng",
    phone: "+234 705 990 1187",
    status: "active",
    projectsCount: 1,
    invoicesCount: 6,
    revenueGenerated: 9800000,
    lastInteraction: daysAgo(1),
    accountOwner: "Chibueze Okafor",
  },
  {
    id: "cli-sol-04",
    workspaceId: "ws-solaris",
    name: "Coral Foods Ltd",
    industry: "FMCG",
    primaryContact: "Patience Umeh",
    email: "patience@coralfoods.ng",
    phone: "+234 813 552 7789",
    status: "dormant",
    projectsCount: 1,
    invoicesCount: 4,
    revenueGenerated: 4100000,
    lastInteraction: daysAgo(95),
    accountOwner: "Amara Nwosu",
  },
  {
    id: "cli-sol-05",
    workspaceId: "ws-solaris",
    name: "Silverline Boutiques",
    industry: "Fashion Retail",
    primaryContact: "Adaeze Okoro",
    email: "adaeze@silverlineboutiques.ng",
    phone: "+234 806 331 5528",
    status: "active",
    projectsCount: 4,
    invoicesCount: 15,
    revenueGenerated: 31800000,
    lastInteraction: daysAgo(3),
    accountOwner: "Chibueze Okafor",
  },
  {
    id: "cli-sol-06",
    workspaceId: "ws-solaris",
    name: "Baywatch Pharmacies",
    industry: "Healthcare Retail",
    primaryContact: "Dr. Kunle Fashola",
    email: "kunle@baywatchpharm.ng",
    phone: "+234 809 774 2210",
    status: "active",
    projectsCount: 2,
    invoicesCount: 8,
    revenueGenerated: 12300000,
    lastInteraction: daysAgo(9),
    accountOwner: "Amara Nwosu",
  },
  {
    id: "cli-sol-07",
    workspaceId: "ws-solaris",
    name: "Goldcrest Supermarket",
    industry: "Retail",
    primaryContact: "Ejiro Ogbeide",
    email: "ejiro@goldcrest.ng",
    phone: "+234 703 118 9982",
    status: "churned",
    projectsCount: 1,
    invoicesCount: 3,
    revenueGenerated: 2600000,
    lastInteraction: daysAgo(210),
    accountOwner: "Amara Nwosu",
  },
  {
    id: "cli-sol-08",
    workspaceId: "ws-solaris",
    name: "Prestige Supermarts",
    industry: "Retail",
    primaryContact: "Halima Yusuf",
    email: "halima@prestigesupermarts.ng",
    phone: "+234 803 221 4590",
    status: "active",
    projectsCount: 1,
    invoicesCount: 2,
    revenueGenerated: 3400000,
    lastInteraction: daysAgo(4),
    accountOwner: "Amara Nwosu",
  },
  // Vertex Logistics Ltd
  {
    id: "cli-vtx-01",
    workspaceId: "ws-vertex",
    name: "Northern Star Traders",
    industry: "Wholesale",
    primaryContact: "Sadiq Bello",
    email: "sadiq@northernstar.ng",
    phone: "+234 705 990 1187",
    status: "active",
    projectsCount: 2,
    invoicesCount: 7,
    revenueGenerated: 18400000,
    lastInteraction: daysAgo(5),
    accountOwner: "Emeka Chukwu",
  },
  {
    id: "cli-vtx-02",
    workspaceId: "ws-vertex",
    name: "Lagos Port Authority Partners",
    industry: "Government / Ports",
    primaryContact: "Chinedu Obasi",
    email: "chinedu@lpap.ng",
    phone: "+234 809 220 4471",
    status: "active",
    projectsCount: 3,
    invoicesCount: 11,
    revenueGenerated: 42600000,
    lastInteraction: daysAgo(1),
    accountOwner: "Grace Adeyemi",
  },
  {
    id: "cli-vtx-03",
    workspaceId: "ws-vertex",
    name: "AgroBridge Exporters",
    industry: "Agriculture Export",
    primaryContact: "Musa Garba",
    email: "musa@agrobridge.ng",
    phone: "+234 706 552 8830",
    status: "active",
    projectsCount: 1,
    invoicesCount: 5,
    revenueGenerated: 9200000,
    lastInteraction: daysAgo(11),
    accountOwner: "Emeka Chukwu",
  },
  {
    id: "cli-vtx-04",
    workspaceId: "ws-vertex",
    name: "Continental Freighters",
    industry: "Freight",
    primaryContact: "Ifeanyi Okpara",
    email: "ifeanyi@continentalfreighters.ng",
    phone: "+234 802 664 1129",
    status: "dormant",
    projectsCount: 1,
    invoicesCount: 3,
    revenueGenerated: 5100000,
    lastInteraction: daysAgo(80),
    accountOwner: "Emeka Chukwu",
  },
  {
    id: "cli-vtx-05",
    workspaceId: "ws-vertex",
    name: "Everline Warehousing",
    industry: "Warehousing",
    primaryContact: "Ronke Adisa",
    email: "ronke@everline.ng",
    phone: "+234 813 774 2201",
    status: "active",
    projectsCount: 2,
    invoicesCount: 6,
    revenueGenerated: 14700000,
    lastInteraction: daysAgo(7),
    accountOwner: "Emeka Chukwu",
  },
  {
    id: "cli-vtx-06",
    workspaceId: "ws-vertex",
    name: "Sahel Bulk Carriers",
    industry: "Bulk Transport",
    primaryContact: "Zainab Umar",
    email: "zainab@sahelbulk.ng",
    phone: "+234 705 118 6634",
    status: "churned",
    projectsCount: 1,
    invoicesCount: 2,
    revenueGenerated: 3300000,
    lastInteraction: daysAgo(180),
    accountOwner: "Grace Adeyemi",
  },
];

export function getClientsForWorkspace(workspaceId: string) {
  return CLIENTS.filter((c) => c.workspaceId === workspaceId);
}
