import type { Expense } from "@/types/domain";
import { daysAgo } from "./dates";

export const EXPENSES: Expense[] = [
  // Solaris Retail Group
  {
    id: "exp-sol-01",
    workspaceId: "ws-solaris",
    category: "Rent",
    department: "Operations",
    vendor: "Lekki Commercial Properties",
    amount: 2200000,
    date: daysAgo(28),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  {
    id: "exp-sol-02",
    workspaceId: "ws-solaris",
    category: "Salaries",
    department: "Operations",
    vendor: "Payroll",
    amount: 9800000,
    date: daysAgo(25),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  {
    id: "exp-sol-03",
    workspaceId: "ws-solaris",
    category: "Marketing",
    department: "Sales & Marketing",
    vendor: "Bloom Digital Agency",
    amount: 1350000,
    date: daysAgo(14),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Tunde Bakare",
  },
  {
    id: "exp-sol-04",
    workspaceId: "ws-solaris",
    category: "Fuel & Transport",
    department: "Logistics",
    vendor: "NNPC Retail",
    amount: 620000,
    date: daysAgo(6),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Tunde Bakare",
  },
  {
    id: "exp-sol-05",
    workspaceId: "ws-solaris",
    category: "Software Subscriptions",
    department: "IT",
    vendor: "Microsoft 365",
    amount: 340000,
    date: daysAgo(3),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  {
    id: "exp-sol-06",
    workspaceId: "ws-solaris",
    category: "Equipment",
    department: "IT",
    vendor: "Computer Warehouse Ltd",
    amount: 1850000,
    date: daysAgo(40),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  {
    id: "exp-sol-07",
    workspaceId: "ws-solaris",
    category: "Office Supplies",
    department: "Operations",
    vendor: "OfficePoint Nigeria",
    amount: 185000,
    date: daysAgo(9),
    status: "pending",
    hasReceipt: false,
    notes: "Awaiting receipt from vendor.",
  },
  {
    id: "exp-sol-08",
    workspaceId: "ws-solaris",
    category: "Utilities",
    department: "Operations",
    vendor: "Eko Electricity Distribution",
    amount: 410000,
    date: daysAgo(17),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Tunde Bakare",
  },
  {
    id: "exp-sol-09",
    workspaceId: "ws-solaris",
    category: "Professional Services",
    department: "Finance",
    vendor: "KPMG Nigeria",
    amount: 2600000,
    date: daysAgo(55),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
    notes: "Annual audit engagement.",
  },
  {
    id: "exp-sol-10",
    workspaceId: "ws-solaris",
    category: "Travel",
    department: "Sales & Marketing",
    vendor: "Air Peace",
    amount: 275000,
    date: daysAgo(11),
    status: "pending",
    hasReceipt: true,
  },
  {
    id: "exp-sol-11",
    workspaceId: "ws-solaris",
    category: "Insurance",
    department: "Operations",
    vendor: "AIICO Insurance",
    amount: 950000,
    date: daysAgo(70),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  {
    id: "exp-sol-12",
    workspaceId: "ws-solaris",
    category: "Maintenance",
    department: "Logistics",
    vendor: "AutoCare Fleet Services",
    amount: 530000,
    date: daysAgo(4),
    status: "rejected",
    hasReceipt: false,
    notes: "Duplicate submission of exp-sol-04.",
  },
  {
    id: "exp-sol-13",
    workspaceId: "ws-solaris",
    category: "Marketing",
    department: "Sales & Marketing",
    vendor: "Instagram Ads",
    amount: 410000,
    date: daysAgo(2),
    status: "pending",
    hasReceipt: true,
  },
  {
    id: "exp-sol-14",
    workspaceId: "ws-solaris",
    category: "Salaries",
    department: "Sales & Marketing",
    vendor: "Payroll",
    amount: 3200000,
    date: daysAgo(25),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Chibueze Okafor",
  },
  // Vertex Logistics Ltd
  {
    id: "exp-vtx-01",
    workspaceId: "ws-vertex",
    category: "Fuel & Transport",
    department: "Fleet Operations",
    vendor: "Total Energies",
    amount: 3400000,
    date: daysAgo(9),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Grace Adeyemi",
  },
  {
    id: "exp-vtx-02",
    workspaceId: "ws-vertex",
    category: "Maintenance",
    department: "Fleet Operations",
    vendor: "TrackFix Auto Services",
    amount: 1250000,
    date: daysAgo(15),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Fatima Bello",
  },
  {
    id: "exp-vtx-03",
    workspaceId: "ws-vertex",
    category: "Salaries",
    department: "Fleet Operations",
    vendor: "Payroll",
    amount: 7600000,
    date: daysAgo(25),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Grace Adeyemi",
  },
  {
    id: "exp-vtx-04",
    workspaceId: "ws-vertex",
    category: "Warehousing",
    department: "Warehousing",
    vendor: "Apapa Storage Facility",
    amount: 1800000,
    date: daysAgo(20),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Grace Adeyemi",
  },
  {
    id: "exp-vtx-05",
    workspaceId: "ws-vertex",
    category: "Software Subscriptions",
    department: "IT",
    vendor: "Fleet Track Pro",
    amount: 290000,
    date: daysAgo(5),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Fatima Bello",
  },
  {
    id: "exp-vtx-06",
    workspaceId: "ws-vertex",
    category: "Insurance",
    department: "Fleet Operations",
    vendor: "AXA Mansard",
    amount: 1650000,
    date: daysAgo(60),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Grace Adeyemi",
  },
  {
    id: "exp-vtx-07",
    workspaceId: "ws-vertex",
    category: "Office Supplies",
    department: "HR",
    vendor: "OfficePoint Nigeria",
    amount: 120000,
    date: daysAgo(8),
    status: "pending",
    hasReceipt: false,
  },
  {
    id: "exp-vtx-08",
    workspaceId: "ws-vertex",
    category: "Professional Services",
    department: "Finance",
    vendor: "PwC Nigeria",
    amount: 2100000,
    date: daysAgo(48),
    status: "approved",
    hasReceipt: true,
    approvedBy: "Grace Adeyemi",
  },
  {
    id: "exp-vtx-09",
    workspaceId: "ws-vertex",
    category: "Utilities",
    department: "Warehousing",
    vendor: "Ikeja Electric",
    amount: 380000,
    date: daysAgo(13),
    status: "pending",
    hasReceipt: true,
  },
  {
    id: "exp-vtx-10",
    workspaceId: "ws-vertex",
    category: "Fuel & Transport",
    department: "Fleet Operations",
    vendor: "Total Energies",
    amount: 2900000,
    date: daysAgo(1),
    status: "rejected",
    hasReceipt: false,
    notes: "Missing fleet manifest for approval.",
  },
];

export function getExpensesForWorkspace(workspaceId: string) {
  return EXPENSES.filter((e) => e.workspaceId === workspaceId);
}
