import type { IncomeRecord } from "@/types/domain";
import { daysAgo } from "./dates";

export const INCOME_RECORDS: IncomeRecord[] = [
  // Solaris Retail Group
  {
    id: "inc-sol-01",
    workspaceId: "ws-solaris",
    date: daysAgo(5),
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    invoiceId: "inv-sol-01",
    amount: 2450000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-88213",
    receivedBy: "Ifeoma Eze",
  },
  {
    id: "inc-sol-02",
    workspaceId: "ws-solaris",
    date: daysAgo(10),
    clientId: "cli-sol-06",
    clientName: "Baywatch Pharmacies",
    invoiceId: "inv-sol-05",
    amount: 1750000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-88104",
    receivedBy: "Ifeoma Eze",
  },
  {
    id: "inc-sol-03",
    workspaceId: "ws-solaris",
    date: daysAgo(8),
    clientId: "cli-sol-02",
    clientName: "Ivory Home Stores",
    invoiceId: "inv-sol-10",
    amount: 2100000,
    paymentMethod: "card",
    referenceNumber: "TRX-88176",
    receivedBy: "Tunde Bakare",
  },
  {
    id: "inc-sol-04",
    workspaceId: "ws-solaris",
    date: daysAgo(15),
    clientId: "cli-sol-03",
    clientName: "Northern Star Traders",
    invoiceId: "inv-sol-14",
    amount: 3400000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-87990",
    receivedBy: "Ifeoma Eze",
  },
  {
    id: "inc-sol-05",
    workspaceId: "ws-solaris",
    date: daysAgo(22),
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    invoiceId: "inv-sol-16",
    amount: 2950000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-87711",
    receivedBy: "Tunde Bakare",
  },
  {
    id: "inc-sol-06",
    workspaceId: "ws-solaris",
    date: daysAgo(2),
    clientId: "cli-sol-05",
    clientName: "Silverline Boutiques",
    amount: 850000,
    paymentMethod: "cash",
    referenceNumber: "TRX-88301",
    receivedBy: "Ifeoma Eze",
    notes: "Partial advance payment ahead of full invoice.",
  },
  {
    id: "inc-sol-07",
    workspaceId: "ws-solaris",
    date: daysAgo(30),
    clientId: "cli-sol-08",
    clientName: "Prestige Supermarts",
    amount: 1600000,
    paymentMethod: "cheque",
    referenceNumber: "TRX-87540",
    receivedBy: "Tunde Bakare",
  },
  {
    id: "inc-sol-08",
    workspaceId: "ws-solaris",
    date: daysAgo(45),
    clientId: "cli-sol-04",
    clientName: "Coral Foods Ltd",
    amount: 720000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-87201",
    receivedBy: "Ifeoma Eze",
  },
  {
    id: "inc-sol-09",
    workspaceId: "ws-solaris",
    date: daysAgo(60),
    clientId: "cli-sol-07",
    clientName: "Goldcrest Supermarket",
    amount: 980000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-86822",
    receivedBy: "Tunde Bakare",
  },
  {
    id: "inc-sol-10",
    workspaceId: "ws-solaris",
    date: daysAgo(1),
    clientId: "cli-sol-06",
    clientName: "Baywatch Pharmacies",
    amount: 430000,
    paymentMethod: "card",
    referenceNumber: "TRX-88340",
    receivedBy: "Ifeoma Eze",
  },
  // Vertex Logistics Ltd
  {
    id: "inc-vtx-01",
    workspaceId: "ws-vertex",
    date: daysAgo(10),
    clientId: "cli-vtx-05",
    clientName: "Everline Warehousing",
    invoiceId: "inv-vtx-04",
    amount: 4100000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-VX-4471",
    receivedBy: "Segun Afolabi",
  },
  {
    id: "inc-vtx-02",
    workspaceId: "ws-vertex",
    date: daysAgo(18),
    clientId: "cli-vtx-01",
    clientName: "Northern Star Traders",
    invoiceId: "inv-vtx-07",
    amount: 3700000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-VX-4322",
    receivedBy: "Fatima Bello",
  },
  {
    id: "inc-vtx-03",
    workspaceId: "ws-vertex",
    date: daysAgo(3),
    clientId: "cli-vtx-04",
    clientName: "Continental Freighters",
    invoiceId: "inv-vtx-11",
    amount: 2050000,
    paymentMethod: "cheque",
    referenceNumber: "TRX-VX-4590",
    receivedBy: "Segun Afolabi",
  },
  {
    id: "inc-vtx-04",
    workspaceId: "ws-vertex",
    date: daysAgo(25),
    clientId: "cli-vtx-02",
    clientName: "Lagos Port Authority Partners",
    amount: 6000000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-VX-4198",
    receivedBy: "Fatima Bello",
    notes: "Milestone 1 payment for warehouse contract.",
  },
  {
    id: "inc-vtx-05",
    workspaceId: "ws-vertex",
    date: daysAgo(35),
    clientId: "cli-vtx-03",
    clientName: "AgroBridge Exporters",
    amount: 1100000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-VX-4055",
    receivedBy: "Segun Afolabi",
  },
  {
    id: "inc-vtx-06",
    workspaceId: "ws-vertex",
    date: daysAgo(50),
    clientId: "cli-vtx-06",
    clientName: "Sahel Bulk Carriers",
    amount: 640000,
    paymentMethod: "cash",
    referenceNumber: "TRX-VX-3902",
    receivedBy: "Fatima Bello",
  },
  {
    id: "inc-vtx-07",
    workspaceId: "ws-vertex",
    date: daysAgo(6),
    clientId: "cli-vtx-01",
    clientName: "Northern Star Traders",
    amount: 1900000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-VX-4602",
    receivedBy: "Segun Afolabi",
  },
];

export function getIncomeForWorkspace(workspaceId: string) {
  return INCOME_RECORDS.filter((i) => i.workspaceId === workspaceId);
}
