import type { Invoice } from "@/types/domain";
import { daysAgo, daysFromNow } from "./dates";

export const INVOICES: Invoice[] = [
  // Solaris Retail Group
  {
    id: "inv-sol-01",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1042",
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    issueDate: daysAgo(35),
    dueDate: daysAgo(5),
    amount: 2450000,
    status: "paid",
  },
  {
    id: "inv-sol-02",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1043",
    clientId: "cli-sol-02",
    clientName: "Ivory Home Stores",
    issueDate: daysAgo(28),
    dueDate: daysAgo(-2),
    amount: 1320000,
    status: "outstanding",
  },
  {
    id: "inv-sol-03",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1044",
    clientId: "cli-sol-05",
    clientName: "Silverline Boutiques",
    issueDate: daysAgo(50),
    dueDate: daysAgo(20),
    amount: 3900000,
    status: "overdue",
  },
  {
    id: "inv-sol-04",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1045",
    clientId: "cli-sol-08",
    clientName: "Prestige Supermarts",
    issueDate: daysAgo(10),
    dueDate: daysFromNow(20),
    amount: 4200000,
    status: "outstanding",
  },
  {
    id: "inv-sol-05",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1046",
    clientId: "cli-sol-06",
    clientName: "Baywatch Pharmacies",
    issueDate: daysAgo(40),
    dueDate: daysAgo(10),
    amount: 1750000,
    status: "paid",
  },
  {
    id: "inv-sol-06",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1047",
    clientId: "cli-sol-03",
    clientName: "Northern Star Traders",
    issueDate: daysAgo(60),
    dueDate: daysAgo(30),
    amount: 2600000,
    status: "overdue",
  },
  {
    id: "inv-sol-07",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1048",
    clientId: "cli-sol-04",
    clientName: "Coral Foods Ltd",
    issueDate: daysAgo(15),
    dueDate: daysFromNow(15),
    amount: 980000,
    status: "outstanding",
  },
  {
    id: "inv-sol-08",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1049",
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    issueDate: daysAgo(5),
    dueDate: daysFromNow(25),
    amount: 3100000,
    status: "outstanding",
  },
  {
    id: "inv-sol-09",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1050",
    clientId: "cli-sol-07",
    clientName: "Goldcrest Supermarket",
    issueDate: daysAgo(75),
    dueDate: daysAgo(45),
    amount: 1450000,
    status: "overdue",
  },
  {
    id: "inv-sol-10",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1051",
    clientId: "cli-sol-02",
    clientName: "Ivory Home Stores",
    issueDate: daysAgo(22),
    dueDate: daysAgo(-8),
    amount: 2100000,
    status: "paid",
  },
  {
    id: "inv-sol-11",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1052",
    clientId: "cli-sol-05",
    clientName: "Silverline Boutiques",
    issueDate: daysAgo(3),
    dueDate: daysFromNow(27),
    amount: 5600000,
    status: "outstanding",
  },
  {
    id: "inv-sol-12",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1053",
    clientId: "cli-sol-06",
    clientName: "Baywatch Pharmacies",
    issueDate: daysAgo(18),
    dueDate: daysFromNow(12),
    amount: 890000,
    status: "outstanding",
  },
  {
    id: "inv-sol-13",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1054",
    clientId: "cli-sol-08",
    clientName: "Prestige Supermarts",
    issueDate: daysAgo(65),
    dueDate: daysAgo(35),
    amount: 1200000,
    status: "overdue",
  },
  {
    id: "inv-sol-14",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1055",
    clientId: "cli-sol-03",
    clientName: "Northern Star Traders",
    issueDate: daysAgo(45),
    dueDate: daysAgo(15),
    amount: 3400000,
    status: "paid",
  },
  {
    id: "inv-sol-15",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1056",
    clientId: "cli-sol-04",
    clientName: "Coral Foods Ltd",
    issueDate: daysAgo(1),
    dueDate: daysFromNow(29),
    amount: 640000,
    status: "draft",
  },
  {
    id: "inv-sol-16",
    workspaceId: "ws-solaris",
    invoiceNumber: "SOL-INV-1057",
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    issueDate: daysAgo(52),
    dueDate: daysAgo(22),
    amount: 2950000,
    status: "paid",
  },
  // Vertex Logistics Ltd
  {
    id: "inv-vtx-01",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2201",
    clientId: "cli-vtx-01",
    clientName: "Northern Star Traders",
    issueDate: daysAgo(30),
    dueDate: daysAgo(0),
    amount: 5200000,
    status: "outstanding",
  },
  {
    id: "inv-vtx-02",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2202",
    clientId: "cli-vtx-02",
    clientName: "Lagos Port Authority Partners",
    issueDate: daysAgo(55),
    dueDate: daysAgo(25),
    amount: 9800000,
    status: "overdue",
  },
  {
    id: "inv-vtx-03",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2203",
    clientId: "cli-vtx-03",
    clientName: "AgroBridge Exporters",
    issueDate: daysAgo(12),
    dueDate: daysFromNow(18),
    amount: 2300000,
    status: "outstanding",
  },
  {
    id: "inv-vtx-04",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2204",
    clientId: "cli-vtx-05",
    clientName: "Everline Warehousing",
    issueDate: daysAgo(40),
    dueDate: daysAgo(10),
    amount: 4100000,
    status: "paid",
  },
  {
    id: "inv-vtx-05",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2205",
    clientId: "cli-vtx-04",
    clientName: "Continental Freighters",
    issueDate: daysAgo(70),
    dueDate: daysAgo(40),
    amount: 1600000,
    status: "overdue",
  },
  {
    id: "inv-vtx-06",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2206",
    clientId: "cli-vtx-06",
    clientName: "Sahel Bulk Carriers",
    issueDate: daysAgo(20),
    dueDate: daysFromNow(10),
    amount: 980000,
    status: "outstanding",
  },
  {
    id: "inv-vtx-07",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2207",
    clientId: "cli-vtx-01",
    clientName: "Northern Star Traders",
    issueDate: daysAgo(48),
    dueDate: daysAgo(18),
    amount: 3700000,
    status: "paid",
  },
  {
    id: "inv-vtx-08",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2208",
    clientId: "cli-vtx-02",
    clientName: "Lagos Port Authority Partners",
    issueDate: daysAgo(6),
    dueDate: daysFromNow(24),
    amount: 12100000,
    status: "outstanding",
  },
  {
    id: "inv-vtx-09",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2209",
    clientId: "cli-vtx-03",
    clientName: "AgroBridge Exporters",
    issueDate: daysAgo(62),
    dueDate: daysAgo(32),
    amount: 1450000,
    status: "overdue",
  },
  {
    id: "inv-vtx-10",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2210",
    clientId: "cli-vtx-05",
    clientName: "Everline Warehousing",
    issueDate: daysAgo(2),
    dueDate: daysFromNow(28),
    amount: 2900000,
    status: "draft",
  },
  {
    id: "inv-vtx-11",
    workspaceId: "ws-vertex",
    invoiceNumber: "VTX-INV-2211",
    clientId: "cli-vtx-04",
    clientName: "Continental Freighters",
    issueDate: daysAgo(33),
    dueDate: daysAgo(3),
    amount: 2050000,
    status: "paid",
  },
];

export function getInvoicesForWorkspace(workspaceId: string) {
  return INVOICES.filter((i) => i.workspaceId === workspaceId);
}
