import type { ITTicket } from "@/types/domain";
import { daysAgo } from "./dates";

export const IT_TICKETS: ITTicket[] = [
  // Solaris Retail Group
  {
    id: "tkt-sol-01",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-301",
    reportedBy: "Ifeoma Eze",
    issue: "POS terminal at Lekki branch freezes during checkout",
    category: "Hardware",
    priority: "high",
    status: "open",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(9),
    resolvedDate: null,
  },
  {
    id: "tkt-sol-02",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-302",
    reportedBy: "Amara Nwosu",
    issue: "Cannot access shared sales pipeline spreadsheet",
    category: "Access & Permissions",
    priority: "medium",
    status: "in_progress",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(4),
    resolvedDate: null,
  },
  {
    id: "tkt-sol-03",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-303",
    reportedBy: "Chibueze Okafor",
    issue: "Email delivery delays from company domain",
    category: "Email & Communication",
    priority: "critical",
    status: "open",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(7),
    resolvedDate: null,
  },
  {
    id: "tkt-sol-04",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-304",
    reportedBy: "Ifeoma Eze",
    issue: "Laptop battery draining unusually fast",
    category: "Hardware",
    priority: "low",
    status: "resolved",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(30),
    resolvedDate: daysAgo(27),
  },
  {
    id: "tkt-sol-05",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-305",
    reportedBy: "Amara Nwosu",
    issue: "VPN disconnects when working remotely",
    category: "Network",
    priority: "medium",
    status: "resolved",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(45),
    resolvedDate: daysAgo(43),
  },
  {
    id: "tkt-sol-06",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-306",
    reportedBy: "Chibueze Okafor",
    issue: "Request new laptop for incoming analyst hire",
    category: "Procurement",
    priority: "low",
    status: "closed",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(60),
    resolvedDate: daysAgo(52),
  },
  {
    id: "tkt-sol-07",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-307",
    reportedBy: "Ifeoma Eze",
    issue: "Invoice PDF export button not responding",
    category: "Software Bug",
    priority: "medium",
    status: "in_progress",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(2),
    resolvedDate: null,
  },
  {
    id: "tkt-sol-08",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-308",
    reportedBy: "Amara Nwosu",
    issue: "Printer at HQ out of toner",
    category: "Hardware",
    priority: "low",
    status: "resolved",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(15),
    resolvedDate: daysAgo(14),
  },
  {
    id: "tkt-sol-09",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-309",
    reportedBy: "Chibueze Okafor",
    issue: "Dashboard loading slowly on mobile network",
    category: "Performance",
    priority: "medium",
    status: "open",
    assignedTo: null,
    createdDate: daysAgo(1),
    resolvedDate: null,
  },
  {
    id: "tkt-sol-10",
    workspaceId: "ws-solaris",
    ticketNumber: "SOL-IT-310",
    reportedBy: "Ifeoma Eze",
    issue: "Two-factor authentication codes not arriving",
    category: "Security",
    priority: "high",
    status: "resolved",
    assignedTo: "Tunde Bakare",
    createdDate: daysAgo(20),
    resolvedDate: daysAgo(19),
  },
  // Vertex Logistics Ltd
  {
    id: "tkt-vtx-01",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-101",
    reportedBy: "Segun Afolabi",
    issue: "GPS fleet tracking hub offline since last night",
    category: "Network",
    priority: "critical",
    status: "open",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(8),
    resolvedDate: null,
  },
  {
    id: "tkt-vtx-02",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-102",
    reportedBy: "Emeka Chukwu",
    issue: "Cannot log into client billing portal",
    category: "Access & Permissions",
    priority: "high",
    status: "in_progress",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(3),
    resolvedDate: null,
  },
  {
    id: "tkt-vtx-03",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-103",
    reportedBy: "Grace Adeyemi",
    issue: "Quarterly report export fails intermittently",
    category: "Software Bug",
    priority: "medium",
    status: "open",
    assignedTo: null,
    createdDate: daysAgo(6),
    resolvedDate: null,
  },
  {
    id: "tkt-vtx-04",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-104",
    reportedBy: "Segun Afolabi",
    issue: "Handheld scanner not syncing warehouse inventory",
    category: "Hardware",
    priority: "medium",
    status: "resolved",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(25),
    resolvedDate: daysAgo(23),
  },
  {
    id: "tkt-vtx-05",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-105",
    reportedBy: "Emeka Chukwu",
    issue: "Email signature branding needs update",
    category: "Email & Communication",
    priority: "low",
    status: "closed",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(40),
    resolvedDate: daysAgo(38),
  },
  {
    id: "tkt-vtx-06",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-106",
    reportedBy: "Grace Adeyemi",
    issue: "Request laptop upgrade for finance lead",
    category: "Procurement",
    priority: "low",
    status: "resolved",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(50),
    resolvedDate: daysAgo(46),
  },
  {
    id: "tkt-vtx-07",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-107",
    reportedBy: "Segun Afolabi",
    issue: "Depot Wi-Fi coverage weak near loading bay",
    category: "Network",
    priority: "medium",
    status: "in_progress",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(5),
    resolvedDate: null,
  },
  {
    id: "tkt-vtx-08",
    workspaceId: "ws-vertex",
    ticketNumber: "VTX-IT-108",
    reportedBy: "Emeka Chukwu",
    issue: "Two-factor authentication codes not arriving",
    category: "Security",
    priority: "high",
    status: "resolved",
    assignedTo: "Fatima Bello",
    createdDate: daysAgo(18),
    resolvedDate: daysAgo(17),
  },
];

export function getITTicketsForWorkspace(workspaceId: string) {
  return IT_TICKETS.filter((t) => t.workspaceId === workspaceId);
}
