import type { Lead } from "@/types/domain";
import { daysAgo, daysFromNow } from "./dates";

export const LEADS: Lead[] = [
  // Solaris Retail Group
  {
    id: "lead-sol-01",
    workspaceId: "ws-solaris",
    company: "Prestige Supermarts",
    contactPerson: "Halima Yusuf",
    email: "halima@prestigesupermarts.ng",
    phone: "+234 803 221 4590",
    source: "Referral",
    expectedValue: 8500000,
    status: "qualified",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(2),
    createdDate: daysAgo(18),
    notes: "Wants a 3-store rollout, budget approved on their end.",
  },
  {
    id: "lead-sol-02",
    workspaceId: "ws-solaris",
    company: "Coastal Mart Ltd",
    contactPerson: "Bimbo Ade",
    email: "bimbo@coastalmart.ng",
    phone: "+234 802 774 1120",
    source: "Trade Fair",
    expectedValue: 3200000,
    status: "contacted",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(5),
    createdDate: daysAgo(12),
  },
  {
    id: "lead-sol-03",
    workspaceId: "ws-solaris",
    company: "Northgate Foods",
    contactPerson: "Aliyu Musa",
    email: "aliyu@northgatefoods.ng",
    phone: "+234 705 331 9284",
    source: "Website",
    expectedValue: 1450000,
    status: "new",
    assignedExecutive: "Chibueze Okafor",
    nextFollowUp: daysFromNow(1),
    createdDate: daysAgo(3),
  },
  {
    id: "lead-sol-04",
    workspaceId: "ws-solaris",
    company: "Greenline Distributors",
    contactPerson: "Ngozi Okeke",
    email: "ngozi@greenline.ng",
    phone: "+234 810 552 6631",
    source: "LinkedIn",
    expectedValue: 6100000,
    status: "qualified",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(4),
    createdDate: daysAgo(21),
  },
  {
    id: "lead-sol-05",
    workspaceId: "ws-solaris",
    company: "Sunbeam Retail",
    contactPerson: "Femi Alabi",
    email: "femi@sunbeamretail.ng",
    phone: "+234 813 004 7712",
    source: "Referral",
    expectedValue: 2750000,
    status: "unqualified",
    assignedExecutive: "Chibueze Okafor",
    nextFollowUp: null,
    createdDate: daysAgo(40),
    notes: "Budget too small for current package tiers.",
  },
  {
    id: "lead-sol-06",
    workspaceId: "ws-solaris",
    company: "Highstreet Traders",
    contactPerson: "Kemi Johnson",
    email: "kemi@highstreettraders.ng",
    phone: "+234 806 220 3345",
    source: "Cold Outreach",
    expectedValue: 4300000,
    status: "contacted",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(7),
    createdDate: daysAgo(9),
  },
  {
    id: "lead-sol-07",
    workspaceId: "ws-solaris",
    company: "Delta Wholesale",
    contactPerson: "Emma Okon",
    email: "emma@deltawholesale.ng",
    phone: "+234 909 118 4471",
    source: "Trade Fair",
    expectedValue: 9800000,
    status: "qualified",
    assignedExecutive: "Chibueze Okafor",
    nextFollowUp: daysFromNow(3),
    createdDate: daysAgo(25),
    notes: "Largest deal in the pipeline this quarter.",
  },
  {
    id: "lead-sol-08",
    workspaceId: "ws-solaris",
    company: "Zenith Marketplace",
    contactPerson: "Chidera Obi",
    email: "chidera@zenithmarketplace.ng",
    phone: "+234 701 668 2290",
    source: "Website",
    expectedValue: 1980000,
    status: "converted",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: null,
    createdDate: daysAgo(55),
  },
  {
    id: "lead-sol-09",
    workspaceId: "ws-solaris",
    company: "Palmgrove Stores",
    contactPerson: "Yetunde Balogun",
    email: "yetunde@palmgrove.ng",
    phone: "+234 802 990 5567",
    source: "Referral",
    expectedValue: 3650000,
    status: "new",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(6),
    createdDate: daysAgo(2),
  },
  {
    id: "lead-sol-10",
    workspaceId: "ws-solaris",
    company: "Ridgeway Mart",
    contactPerson: "Obinna Uche",
    email: "obinna@ridgewaymart.ng",
    phone: "+234 815 447 1183",
    source: "LinkedIn",
    expectedValue: 5200000,
    status: "contacted",
    assignedExecutive: "Chibueze Okafor",
    nextFollowUp: daysFromNow(9),
    createdDate: daysAgo(14),
  },
  {
    id: "lead-sol-11",
    workspaceId: "ws-solaris",
    company: "Bright Foods Nigeria",
    contactPerson: "Rita Nnamdi",
    email: "rita@brightfoods.ng",
    phone: "+234 703 552 8890",
    source: "Cold Outreach",
    expectedValue: 2100000,
    status: "unqualified",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: null,
    createdDate: daysAgo(60),
  },
  {
    id: "lead-sol-12",
    workspaceId: "ws-solaris",
    company: "Metro Grocers",
    contactPerson: "Daniel Peters",
    email: "daniel@metrogrocers.ng",
    phone: "+234 812 300 9921",
    source: "Trade Fair",
    expectedValue: 7300000,
    status: "qualified",
    assignedExecutive: "Amara Nwosu",
    nextFollowUp: daysFromNow(1),
    createdDate: daysAgo(16),
  },
  // Vertex Logistics Ltd
  {
    id: "lead-vtx-01",
    workspaceId: "ws-vertex",
    company: "Cargomax Freight",
    contactPerson: "Aisha Suleiman",
    email: "aisha@cargomax.ng",
    phone: "+234 803 771 2246",
    source: "Referral",
    expectedValue: 12500000,
    status: "qualified",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: daysFromNow(3),
    createdDate: daysAgo(20),
    notes: "National distribution contract, RFP stage.",
  },
  {
    id: "lead-vtx-02",
    workspaceId: "ws-vertex",
    company: "Portline Shipping",
    contactPerson: "Michael Osei",
    email: "michael@portline.com",
    phone: "+234 809 118 3320",
    source: "Trade Fair",
    expectedValue: 5400000,
    status: "contacted",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: daysFromNow(5),
    createdDate: daysAgo(11),
  },
  {
    id: "lead-vtx-03",
    workspaceId: "ws-vertex",
    company: "Kaduna AgroExports",
    contactPerson: "Ibrahim Lawal",
    email: "ibrahim@kadunaagro.ng",
    phone: "+234 706 442 9910",
    source: "Website",
    expectedValue: 3100000,
    status: "new",
    assignedExecutive: "Grace Adeyemi",
    nextFollowUp: daysFromNow(2),
    createdDate: daysAgo(4),
  },
  {
    id: "lead-vtx-04",
    workspaceId: "ws-vertex",
    company: "Swiftlink Couriers",
    contactPerson: "Peace Okonkwo",
    email: "peace@swiftlink.ng",
    phone: "+234 810 227 6631",
    source: "LinkedIn",
    expectedValue: 2200000,
    status: "unqualified",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: null,
    createdDate: daysAgo(45),
  },
  {
    id: "lead-vtx-05",
    workspaceId: "ws-vertex",
    company: "Blueharbor Marine",
    contactPerson: "Tolu Aransiola",
    email: "tolu@blueharbor.com",
    phone: "+234 802 664 5521",
    source: "Cold Outreach",
    expectedValue: 8900000,
    status: "qualified",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: daysFromNow(6),
    createdDate: daysAgo(19),
  },
  {
    id: "lead-vtx-06",
    workspaceId: "ws-vertex",
    company: "Northern Star Traders",
    contactPerson: "Sadiq Bello",
    email: "sadiq@northernstar.ng",
    phone: "+234 705 990 1187",
    source: "Referral",
    expectedValue: 4600000,
    status: "converted",
    assignedExecutive: "Grace Adeyemi",
    nextFollowUp: null,
    createdDate: daysAgo(50),
  },
  {
    id: "lead-vtx-07",
    workspaceId: "ws-vertex",
    company: "Everline Warehousing",
    contactPerson: "Ronke Adisa",
    email: "ronke@everline.ng",
    phone: "+234 813 774 2201",
    source: "Trade Fair",
    expectedValue: 6700000,
    status: "contacted",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: daysFromNow(8),
    createdDate: daysAgo(13),
  },
  {
    id: "lead-vtx-08",
    workspaceId: "ws-vertex",
    company: "Delta Cold Chain",
    contactPerson: "Uche Nnaji",
    email: "uche@deltacoldchain.ng",
    phone: "+234 909 663 1145",
    source: "Website",
    expectedValue: 3900000,
    status: "new",
    assignedExecutive: "Emeka Chukwu",
    nextFollowUp: daysFromNow(1),
    createdDate: daysAgo(5),
  },
  {
    id: "lead-vtx-09",
    workspaceId: "ws-vertex",
    company: "Apex Rail Cargo",
    contactPerson: "Bashir Danjuma",
    email: "bashir@apexrailcargo.ng",
    phone: "+234 807 552 7783",
    source: "LinkedIn",
    expectedValue: 15200000,
    status: "qualified",
    assignedExecutive: "Grace Adeyemi",
    nextFollowUp: daysFromNow(4),
    createdDate: daysAgo(23),
    notes: "Highest-value opportunity this quarter for Vertex.",
  },
];

export function getLeadsForWorkspace(workspaceId: string) {
  return LEADS.filter((l) => l.workspaceId === workspaceId);
}
