import type { Opportunity } from "@/types/domain";
import { daysFromNow } from "./dates";

export const OPPORTUNITIES: Opportunity[] = [
  // Solaris Retail Group
  {
    id: "opp-sol-01",
    workspaceId: "ws-solaris",
    name: "Zenith Marketplace — Q3 Restock Program",
    clientId: "cli-sol-01",
    clientName: "Zenith Marketplace",
    estimatedValue: 6200000,
    probability: 70,
    expectedCloseDate: daysFromNow(12),
    owner: "Amara Nwosu",
    stage: "proposal_sent",
  },
  {
    id: "opp-sol-02",
    workspaceId: "ws-solaris",
    name: "Ivory Home Stores — 2-Branch Expansion",
    clientId: "cli-sol-02",
    clientName: "Ivory Home Stores",
    estimatedValue: 4100000,
    probability: 55,
    expectedCloseDate: daysFromNow(20),
    owner: "Amara Nwosu",
    stage: "qualified",
  },
  {
    id: "opp-sol-03",
    workspaceId: "ws-solaris",
    name: "Prestige Supermarts — 3-Store Rollout",
    clientId: "cli-sol-08",
    clientName: "Prestige Supermarts",
    estimatedValue: 8500000,
    probability: 80,
    expectedCloseDate: daysFromNow(9),
    owner: "Amara Nwosu",
    stage: "negotiation",
  },
  {
    id: "opp-sol-04",
    workspaceId: "ws-solaris",
    name: "Coral Foods — Cold Storage Supply Deal",
    clientId: "cli-sol-04",
    clientName: "Coral Foods Ltd",
    estimatedValue: 2900000,
    probability: 35,
    expectedCloseDate: daysFromNow(30),
    owner: "Chibueze Okafor",
    stage: "new",
  },
  {
    id: "opp-sol-05",
    workspaceId: "ws-solaris",
    name: "Silverline Boutiques — Seasonal Collection",
    clientId: "cli-sol-05",
    clientName: "Silverline Boutiques",
    estimatedValue: 5400000,
    probability: 90,
    expectedCloseDate: daysFromNow(4),
    owner: "Chibueze Okafor",
    stage: "negotiation",
  },
  {
    id: "opp-sol-06",
    workspaceId: "ws-solaris",
    name: "Baywatch Pharmacies — Supply Renewal",
    clientId: "cli-sol-06",
    clientName: "Baywatch Pharmacies",
    estimatedValue: 3300000,
    probability: 100,
    expectedCloseDate: daysFromNow(-6),
    owner: "Amara Nwosu",
    stage: "won",
  },
  {
    id: "opp-sol-07",
    workspaceId: "ws-solaris",
    name: "Goldcrest Supermarket — Win-Back Offer",
    clientId: "cli-sol-07",
    clientName: "Goldcrest Supermarket",
    estimatedValue: 1800000,
    probability: 0,
    expectedCloseDate: daysFromNow(-18),
    owner: "Amara Nwosu",
    stage: "lost",
  },
  {
    id: "opp-sol-08",
    workspaceId: "ws-solaris",
    name: "Northern Star Traders — Bulk Order Contract",
    clientId: "cli-sol-03",
    clientName: "Northern Star Traders",
    estimatedValue: 9800000,
    probability: 60,
    expectedCloseDate: daysFromNow(15),
    owner: "Chibueze Okafor",
    stage: "qualified",
  },
  {
    id: "opp-sol-09",
    workspaceId: "ws-solaris",
    name: "Coastal Mart Ltd — New Account",
    clientId: "cli-sol-02",
    clientName: "Coastal Mart Ltd",
    estimatedValue: 3200000,
    probability: 25,
    expectedCloseDate: daysFromNow(35),
    owner: "Amara Nwosu",
    stage: "new",
  },
  {
    id: "opp-sol-10",
    workspaceId: "ws-solaris",
    name: "Delta Wholesale — Master Distribution Deal",
    clientId: "cli-sol-03",
    clientName: "Delta Wholesale",
    estimatedValue: 9800000,
    probability: 65,
    expectedCloseDate: daysFromNow(22),
    owner: "Chibueze Okafor",
    stage: "proposal_sent",
  },
  {
    id: "opp-sol-11",
    workspaceId: "ws-solaris",
    name: "Metro Grocers — Fresh Produce Line",
    clientId: "cli-sol-01",
    clientName: "Metro Grocers",
    estimatedValue: 7300000,
    probability: 50,
    expectedCloseDate: daysFromNow(17),
    owner: "Amara Nwosu",
    stage: "qualified",
  },
  {
    id: "opp-sol-12",
    workspaceId: "ws-solaris",
    name: "Greenline Distributors — Regional Supply",
    clientId: "cli-sol-04",
    clientName: "Greenline Distributors",
    estimatedValue: 6100000,
    probability: 100,
    expectedCloseDate: daysFromNow(-2),
    owner: "Amara Nwosu",
    stage: "won",
  },
  // Vertex Logistics Ltd
  {
    id: "opp-vtx-01",
    workspaceId: "ws-vertex",
    name: "Lagos Port Authority — Warehouse Contract",
    clientId: "cli-vtx-02",
    clientName: "Lagos Port Authority Partners",
    estimatedValue: 15200000,
    probability: 75,
    expectedCloseDate: daysFromNow(14),
    owner: "Emeka Chukwu",
    stage: "proposal_sent",
  },
  {
    id: "opp-vtx-02",
    workspaceId: "ws-vertex",
    name: "AgroBridge Exporters — Cold Chain Fleet",
    clientId: "cli-vtx-03",
    clientName: "AgroBridge Exporters",
    estimatedValue: 6700000,
    probability: 60,
    expectedCloseDate: daysFromNow(19),
    owner: "Emeka Chukwu",
    stage: "qualified",
  },
  {
    id: "opp-vtx-03",
    workspaceId: "ws-vertex",
    name: "Cargomax Freight — National Distribution",
    clientId: "cli-vtx-01",
    clientName: "Cargomax Freight",
    estimatedValue: 12500000,
    probability: 85,
    expectedCloseDate: daysFromNow(7),
    owner: "Emeka Chukwu",
    stage: "negotiation",
  },
  {
    id: "opp-vtx-04",
    workspaceId: "ws-vertex",
    name: "Everline Warehousing — Storage Expansion",
    clientId: "cli-vtx-05",
    clientName: "Everline Warehousing",
    estimatedValue: 5400000,
    probability: 40,
    expectedCloseDate: daysFromNow(25),
    owner: "Emeka Chukwu",
    stage: "new",
  },
  {
    id: "opp-vtx-05",
    workspaceId: "ws-vertex",
    name: "Continental Freighters — Route Renewal",
    clientId: "cli-vtx-04",
    clientName: "Continental Freighters",
    estimatedValue: 4200000,
    probability: 100,
    expectedCloseDate: daysFromNow(-8),
    owner: "Grace Adeyemi",
    stage: "won",
  },
  {
    id: "opp-vtx-06",
    workspaceId: "ws-vertex",
    name: "Sahel Bulk Carriers — Contract Renewal",
    clientId: "cli-vtx-06",
    clientName: "Sahel Bulk Carriers",
    estimatedValue: 2600000,
    probability: 0,
    expectedCloseDate: daysFromNow(-22),
    owner: "Emeka Chukwu",
    stage: "lost",
  },
  {
    id: "opp-vtx-07",
    workspaceId: "ws-vertex",
    name: "Apex Rail Cargo — Multi-Year Freight Deal",
    clientId: "cli-vtx-02",
    clientName: "Apex Rail Cargo",
    estimatedValue: 15200000,
    probability: 55,
    expectedCloseDate: daysFromNow(28),
    owner: "Grace Adeyemi",
    stage: "qualified",
  },
  {
    id: "opp-vtx-08",
    workspaceId: "ws-vertex",
    name: "Blueharbor Marine — Port Handling Services",
    clientId: "cli-vtx-05",
    clientName: "Blueharbor Marine",
    estimatedValue: 8900000,
    probability: 65,
    expectedCloseDate: daysFromNow(11),
    owner: "Emeka Chukwu",
    stage: "proposal_sent",
  },
  {
    id: "opp-vtx-09",
    workspaceId: "ws-vertex",
    name: "Portharbor Exports — Export Handling Contract",
    clientId: "cli-vtx-04",
    clientName: "Portharbor Exports",
    estimatedValue: 10300000,
    probability: 90,
    expectedCloseDate: daysFromNow(5),
    owner: "Grace Adeyemi",
    stage: "negotiation",
  },
];

export function getOpportunitiesForWorkspace(workspaceId: string) {
  return OPPORTUNITIES.filter((o) => o.workspaceId === workspaceId);
}
